### PR TITLE
feature: add autocompactionInterval

### LINKED ISSUE #2: Large messages with infrequent restarts result in a jammed Store
We have a case where we use nedb Store for queuing outgoing rather verbose JSON messages.

If you publish enough data even in a perfectly functioning system (the mqtt server is always reachable) the outgoing nedb store grows so large that nedb fails to reopen it upon system/mqtt client restart and the system can not recover from this condition, even if all the outgoing messages have been sent ok.

### PR DESCRIPTION
**Pull request by tkurki**
Add autocompactionInterval options properties to incoming and
outgoing stores.

Fixes #2.

Tested manually, as the mocha tests are broken in master.

### CODE REVIEW

**Comment by tkurki** [comment]
Any comments on this?

**Comment by behrad** [comment]
thank you @tkurki

**Comment by tkurki** [comment]
No problem! Please remember to publish to npm as well, isn’t there yet afai can see.

**Comment by tkurki** [comment]
Pretty please? Not very motivating to contribute upstream if the result is never published, forking would be less effort for me but worse overall.

**Comment by behrad** [comment]
Done!

**Comment by mugul** [comment]
Hi there!

Does the autoCompactionInterval helps me to reduce the size of the file and clean the deleted rows? I got an error with a "toString()" while trying to restart the process because the file was way too big... The software i'm using should be alive for months without restart.

And the second question, and most important... it's value should be in milliseconds or seconds?... I think it should be milliseconds but that "60" in the readme got me a little confused.

Thanks for your support and sorry if this is not the way to ask.

**Comment by tkurki** [comment]
Value is in milliseconds.

Yes this will reduce the file size and get rid of the deleted rows, but be aware that nedb will still load the whole database into memory. If you lose mqtt server connectivity so that the outgoing queue size gets huge (lots of large messages) you may be again in trouble. Guess how I know...switched to mqtt-level-store for my use case.

**Comment by mugul** [comment]
Thank you very much for your reply and advice.

Have a nice day!

**Pull request merged**
